uploads = []
generated = []

[[outputs]]
id = "Hq65MznJ4q0TlYiQXdO3V"
uri = "file://pqc-atlas-slides.tar.gz"
type = "unspecified"
title = "PQC-Atlas Conference Slides (Web Archive)"

[[outputs]]
id = "BDPkrHUVBbmHZ_FzoGHYd"
uri = "file://PQC-Atlas-Conference-Deck.pptx"
type = "slides"
title = "PQC-Atlas Conference Deck (PowerPoint)"
